version: "3.6"

services:
  app-service:
    build: ./server/services/app
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: "production"

  user-service:
    build: ./server/services/users
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}
      JWT_SECRET: ${JWT_SECRET}

  orchestrator-service:
    build: ./orchestrator/orchestrator-graphql
    ports:
      - "80:4000"
    environment:
      PORT: 4000
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
